# Generated by Django 2.0 on 2018-01-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.AddField(
            model_name='actor',
            name='birthdate',
            field=models.CharField(default='1/1', max_length=300),
        ),
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='actor',
            name='socialMedia',
            field=models.CharField(default=' ', max_length=11),
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
