# Generated by Django 2.0 on 2018-01-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=500)),
                ('award_date', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=500)),
                ('movie_date', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='actor',
            name='socialMedia',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.Actor'),
        ),
        migrations.AddField(
            model_name='award',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.Actor'),
        ),
    ]
