# Generated by Django 2.0 on 2018-01-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0005_prize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='PrizeDate',
            new_name='prizeDate',
        ),
    ]
