# Generated by Django 2.0 on 2018-01-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0006_auto_20180129_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='actor',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
    ]
