# Generated by Django 2.0 on 2018-02-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0009_movie_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(default=' ', max_length=1000, upload_to=''),
        ),
    ]
