# Generated by Django 2.0 on 2018-02-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0010_auto_20180204_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
