# Generated by Django 2.0 on 2018-02-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0011_auto_20180204_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(default=' ', max_length=1000, upload_to=''),
        ),
    ]
