# Generated by Django 2.0 on 2018-02-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0019_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='actor_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
